### ISSUE TITLE
CommandExecutor is empty

### ISSUE THREAD

**Issue by komodo108** [BtoBastian/sdcf4j#12]
This looks amazing, however has a critical issue, which I described below:

In CommandExecutor.java (sdcf4j-core), the class has no content.
The commands then don't function as all commands are required to implement the CommandExecutor. (https://github.com/BtoBastian/Javacord).

**Comment by BtoBastian** [comment]
Hey,
it's intended for the interface to be empty.
Just implement it and add your commands.
