### ISSUE TITLE
Some improvement suggestions

### ISSUE THREAD

**Issue by Vampire** [BtoBastian/sdcf4j#23]
If you prefer one ticket per idea, I'll do so, for now you have them here as list. :-)

- Where an array is allowed in a command handler method, also allow a `Collection`
- Instead of `Object[]` allow `LongOrUserOrChannelOrString[]` (different name of course) that has `asUser()`, `asChannel()` and `asLong()` which return `Optional`s and `asString()` which returns the string
- Maybe use `BigInteger` instead of `Long` to support arbitrary long numbers
- Allow `Optional<GroupChannel>` and so on as parameters and directly put the `Optional` in there instead of using `orElse(null)`, mapping should be by type parameter if possible or if not, by parameter name if possible (In Java 8 you can use a java compiler switch to make the parameter names available during runtime)
- Check for jsr305 annotation `@Nonnull` on a parameter and  if the parameter is annotated with it, but you would give `null` or an empty `Optional` to it, either throw an exception or make a debug log statement and just do not call the handler
- The handler uses `method.setAccessible(true)`, but currently only `public` command methods are found anyway, I'd either remove that unnecessary call or even better also support non-public methods by using `getDeclaredMethods()` instead of `getMethods()`
- Maybe replace
`String[] splitMessage = message.getContent().split(" ");`
 by 
`String[] splitMessage = message.getContent().split(" +");`
 or even by 
`String[] splitMessage = message.getContent().split("\s+");`
- Allow default prefixes and aliases with spaces, so that you can e. g. make `t ` as the prefix for a translation bot and so on
- When the default prefix is changed at runtime, also update the command registry
- Make the prefix configurable by server or maybe even by channel
- provide a way to deregister the command handler

**Comment by BtoBastian** [comment]
Hey, thank you for the suggestions. :-)
`If you prefer one ticket per idea, I'll do so`
Yes, please. :)

**Comment by Vampire** [comment]
split
