### ISSUE TITLE
Doesn't work with the latest JDA

### ISSUE THREAD

**Issue by raxixor** [BtoBastian/sdcf4j#4]
Title says it all.

Quick edit: Well, the non-development version doesn't. I'll probably be changing to the development version now that I found it.

Quick edit 2: Please don't hate me.

**Comment by BtoBastian** [comment]
I hate you! :p
Did the dev-version work? It's untested.

**Comment by raxixor** [comment]
No commands ran. I'm putting the source up sometime soon.

On Fri, Jan 13, 2017 at 8:22 PM, Bastian Oppermann <notifications@github.com

**Comment by BtoBastian** [comment]
I'll try to test it tomorrow and then release 1.0.4.

**Comment by raxixor** [comment]
Thanks.

**Comment by BtoBastian** [comment]
1.0.4 now supports the latest JDA 3 version :)
https://github.com/BtoBastian/sdcf4j/pull/5
