### ISSUE TITLE
Save permissions for reboot

### ISSUE THREAD

**Issue by tankerkiller125** [BtoBastian/sdcf4j#9]
Currently, the library does not save what permissions users have and after a reboot, that information is lost. It would be very helpful if the library either saved this data itself somehow or if there was at least a way to list all the users, guilds and permissions. An example of JSON that might be outputted after some processing this function would be:

```json
[
    {
        "user": "tanerkiller125",
        "id": 108258763407908860,
        "guild": 108234208916348930,
        "permissions": [
            "admin.changeGame",
            "admin.changeAvatar",
            "admin.changeName"
        ]
    },
    {
        "user": "Wild",
        "id": 101656373493772290,
        "guild": 108234208916348930,
        "permissions": [
            "admin.changeGame"
        ]
    }
]
```

Then on every reboot, the library could load the file and apply the permissions.

so we might make the functions part of the CommandHandler as the permissions something like `saveUserPermissions(String location)` and `loadUserPermissions(String location)`

**Comment by tankerkiller125** [comment]
After some further looking at the CommandHanlder I'm thinking that making the Permissions HashMap a returnable function like the `getCommands()` function does. This would at least make it possible for the developer to save and load permission files.

**Comment by BtoBastian** [comment]
Hey,
adding a new command to get all permissions would be no problem and I don't see any reason to not add it. :)
However, I won't add the suggested save method, as I think that's​ the job of the developers to choose the right way of saving the permissions. Some might want to save it in a flat file (like the suggested JSON file), some might want to use a database and others just hardcoded it into their source code.

**Comment by BtoBastian** [comment]
Hey,
I added a new #getPermissions() method to the CommandHandler class: [JavaDocs](http://ci.ketrwu.de/job/sdcf4j/job/master/javadoc/de/btobastian/sdcf4j/CommandHandler.html#getPermissions--)
